services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: express-server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/uploads
    restart: always

  client:
    build: ./client
    container_name: react-client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    restart: always

volumes:
  mongo_data:
